from _typeshed import Incomplete
from brother_ql.backends import (
    available_backends as available_backends,
    backend_factory as backend_factory,
)
from brother_ql.devicedependent import (
    DIE_CUT_LABEL as DIE_CUT_LABEL,
    ENDLESS_LABEL as ENDLESS_LABEL,
    ROUND_DIE_CUT_LABEL as ROUND_DIE_CUT_LABEL,
    label_sizes as label_sizes,
    label_type_specs as label_type_specs,
    models as models,
)

logger: Incomplete
printer_help: str

def cli(ctx, *args, **kwargs) -> None: ...
def discover(ctx) -> None: ...
def discover_and_list_available_devices(backend) -> None: ...
def info(ctx, *args, **kwargs) -> None: ...
def models_cmd(ctx, *args, **kwargs) -> None: ...
def labels(ctx, *args, **kwargs) -> None: ...
def env(ctx, *args, **kwargs): ...
def print_cmd(ctx, *args, **kwargs) -> None: ...
def analyze_cmd(ctx, *args, **kwargs) -> None: ...
def send_cmd(ctx, *args, **kwargs) -> None: ...
