from _typeshed import Incomplete
from collections.abc import Generator

logger: Incomplete

class ElementsManager:
    DEFAULT_ELEMENTS: Incomplete
    ELEMENT_NAME: str
    def __init__(self, elements: Incomplete | None = ...) -> None: ...
    def register(self, element, pos: int = ...) -> None: ...
    def deregister(self, element) -> None: ...
    def iter_identifiers(self) -> Generator[Incomplete, None, None]: ...
    def iter_elements(self) -> Generator[Incomplete, None, None]: ...
