from _typeshed import Incomplete

logger: Incomplete

def list_available_devices() -> None: ...

class BrotherQLBackendGeneric:
    write_dev: Incomplete
    read_dev: Incomplete
    def __init__(self, device_specifier) -> None: ...
    def write(self, data) -> None: ...
    def read(self, length: int = ...): ...
    def dispose(self) -> None: ...
    def __del__(self) -> None: ...
